name = "fringe"
type = "webpack"
account_id = "${{ secrets.account }}"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
vars = {GRAPHQL_API = "https://api.spacex.land/graphql"}